name: Docker

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        moodle-version:
          - "4.0"
          - "4.1"
          - "4.2"
          - "4.3"
          - "4.4"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract metadata
        uses: docker/metadata-action@v5
        with:
          images: ${{ github.repository_owner }}/moodle
          tags: ${{ matrix.moodle-version }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{ defaultContext }}:${{ matrix.moodle-version }}/debian-12"
          build-args: |
            WITH_ALL_LOCALES=yes
          tags: ${{ env.DOCKER_METADATA_OUTPUT_TAGS }}
          push: true
          cache-from: type=gha,scope=${{ matrix.moodle-version }}
          cache-to: type=gha,mode=max,scope=${{ matrix.moodle-version }}
